openapi: 3.1.1
info:
  title: Oxymas API - Control de Cilindros
  version: 1.0.0

paths:
  /control-cilindros:
    post:
      summary: Recibe los datos de la tabla de control de cilindros
      operationId: recibirControlCilindros
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                registros:
                  type: array
                  items:
                    type: object
                    properties:
                      NOMBRE:
                        type: string
                      CILINDRO:
                        type: string
                      PRODUCTO:
                        type: string
                      CAPACIDAD:
                        type: string
                      RECIBO_ENTREGA:
                        type: string
                      FECHA_ENTREGA:
                        type: string
                      RECIBO_DEVOLUCION:
                        type: string
                      FECHA_DEVOLUCION:
                        type: string
                      PROPIEDAD:
                        type: string
                      NOTA:
                        type: string
      responses:
        '200':
          description: Datos recibidos correctamente

servers:
  - url: https://oxymas.com/api
