openapi: 3.1.0
info:
  title: OXYMAS - Webhook para Instrucciones e Informes
  version: 1.2.0
paths:
  /:
    post:
      summary: Procesar mensajes desde OXYMAS
      operationId: recibirMensajeOxymas
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                mensaje:
                  type: string
                cilindro:
                  type: string
                instruction:
                  type: string
                action:
                  type: string
                  enum:
                    - Guardar instrucción
                    - Guardar informe
                    - Consultar informe
              required:
                - action
      responses:
        "200":
          description: Éxito
        "500":
          description: Error interno
servers:
  - url: https://api.oxymas.com/api

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
